### ISSUE TITLE
Apply BEM to People's private CSS

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/People#22]
This app contains globally applied CSS rules in stylesheets: 
- https://github.com/StarcounterSamples/People/blob/52e0f76cb1ef461816eea6bfc818ccdc1df96cba/src/People/wwwroot/People/css/standalone.css

It also contains inline CSS in HTML templates: 
- https://github.com/StarcounterSamples/People/blob/master/src/People/wwwroot/People/viewmodels/ConfirmDialogPage.html
- https://github.com/StarcounterSamples/People/blob/master/src/People/wwwroot/People/viewmodels/OrganizationPage.html

All private CSS should be converted to BEM-style CSS classes defined in a stylesheet, according to the intent started in the issue https://github.com/Starcounter/Starcounter/issues/3450 and explained in the article http://starcounter.io/guides/web/avoiding-css-conflicts/

**Comment by warpech** [comment]
Related #50

**Comment by threezool** [comment]
Fixed in #62

**Comment by warpech** [comment]
This is not fixed yet. Please read up http://starcounter.io/guides/apps/css-bem/:

`.people-top-menu ul li a` is not a correct BEM class/selector. It should be `.people-top-menu__link`

This applies to other selectors in stylesheets as well.

**Comment by mmnosek** [comment]
I wait for this fix in develop as well :)

**Comment by warpech** [comment]
Solution tracked in PR #65

**Comment by warpech** [comment]
Closing as done.
